const fs = require('fs');

const missingTranslations = {
  en: {
    // ── Perks ──
    perk1_title: 'Handpicked homes',
    perk1_desc: 'Every residence is personally inspected and styled for comfort, space and natural light.',
    perk2_title: 'Keyless check-in',
    perk2_desc: 'Arrive on your schedule with a private smart-lock PIN — no waiting, no lobby, no hassle.',
    perk3_title: 'Concierge on call',
    perk3_desc: 'Restaurant bookings, airport transfers, grocery delivery — our local team handles the details so you don\'t have to.',
    perk4_title: 'Transparent pricing',
    perk4_desc: 'The price you see is the price you pay. No hidden fees, no surprises at checkout.',
    // ── Member Modal ──
    member_eyebrow: 'Private access',
    member_title: 'Make Dubai yours.',
    member_sub: 'Save residences, keep your preferences close and hear about new Biazo vacation homes first.',
    member_email: 'Email address',
    member_password: 'Password',
    member_password_hint: 'At least 6 characters',
    member_create_btn: 'CREATE MEMBER PROFILE',
    member_already: 'Already a member? Sign in with your email.',
    member_welcome: 'Welcome to Biazo.',
    member_welcome_sub: 'Your member profile is ready. We\'ll send the latest residences and considered city notes to',
    member_continue_btn: 'CONTINUE',
    // ── CTA Section ──
    cta_eyebrow: 'A little closer',
    cta_title: 'The best of Dubai, kept in your pocket.',
    cta_btn: 'JOIN BIAZO MEMBERS',
    // ── Settings modal (additional) ──
    settings_preferences: 'PREFERENCES',
    settings_live: 'LIVE',
    settings_updated: 'updated',
    settings_fetching: 'Fetching live rates…',
    // ── Contact page ──
    contact_nav_home: 'Home',
    contact_nav_details: 'Contact details',
    contact_nav_enquiry: 'Make an enquiry',
    contact_nav_back: 'BACK TO BIAZO',
    contact_hero_eyebrow: 'The door is open',
    contact_hero_title1: "Let's make",
    contact_hero_title2: 'space for you.',
    contact_hero_intro: 'Whether you are planning a considered stay, looking after a Dubai home, or simply want a local point of view, our team is close by.',
    contact_details_eyebrow: 'Find us here',
    contact_details_title1: 'A real person,',
    contact_details_title2: 'in your corner.',
    contact_details_sub: 'No call centres. No hand-offs. Just a local team with a good sense of place and time.',
    contact_whatsapp: 'WhatsApp',
    contact_email: 'Email',
    contact_office: 'Office',
    contact_dubai_uae: 'Dubai, UAE',
    contact_po_box: 'P.O. Box 118-885',
    contact_enquiry_eyebrow: 'A little context helps',
    contact_enquiry_title1: 'Tell us what',
    contact_enquiry_title2: 'you need.',
    contact_enquiry_sub: 'Leave a few details and we will come back to you personally. For an immediate answer, use WhatsApp above.',
    contact_enquiry_call: 'CALL THE BIAZO DESK',
    contact_sent_title: 'We have your note.',
    contact_sent_sub: 'Thank you. A Biazo Vacation Homes specialist will be in touch shortly.',
    contact_send_another: 'SEND ANOTHER NOTE',
    contact_form_name: 'Your name',
    contact_form_name_ph: 'How should we address you?',
    contact_form_email: 'Email or WhatsApp',
    contact_form_email_ph: 'The best way to reach you',
    contact_form_help: 'What can we help with?',
    contact_form_help_ph: 'A residence, your property, a question about Dubai...',
    contact_form_submit: 'SEND YOUR NOTE',
    contact_footer_desc: 'Private residences and local perspective, for the way you want to experience Dubai.',
  },
  ar: {
    perk1_title: 'منازل منتقاة بعناية',
    perk1_desc: 'يتم فحص كل مسكن شخصيًا وتجهيزه ليوفر الراحة والمساحة والإضاءة الطبيعية.',
    perk2_title: 'تسجيل وصول بدون مفتاح',
    perk2_desc: 'صل في وقتك الخاص برمز قفل ذكي خاص — بدون انتظار أو بهو أو عناء.',
    perk3_title: 'خدمة كونسيرج عند الطلب',
    perk3_desc: 'حجوزات المطاعم، انتقالات المطار، توصيل البقالة — فريقنا المحلي يتولى التفاصيل حتى لا تضطر لذلك.',
    perk4_title: 'أسعار شفافة',
    perk4_desc: 'السعر الذي تراه هو السعر الذي تدفعه. لا توجد رسوم خفية أو مفاجآت عند تسجيل المغادرة.',
    member_eyebrow: 'وصول خاص',
    member_title: 'اجعل دبي مدينتك.',
    member_sub: 'احفظ المساكن، أبقِ تفضيلاتك قريبة واسمع عن منازل عطلات بيازو الجديدة أولاً.',
    member_email: 'عنوان البريد الإلكتروني',
    member_password: 'كلمة المرور',
    member_password_hint: 'على الأقل 6 أحرف',
    member_create_btn: 'إنشاء ملف تعريف عضو',
    member_already: 'هل أنت عضو بالفعل؟ سجل الدخول ببريدك الإلكتروني.',
    member_welcome: 'مرحبًا بك في بيازو.',
    member_welcome_sub: 'ملف تعريف العضو الخاص بك جاهز. سنرسل أحدث المساكن وملاحظات المدينة المدروسة إلى',
    member_continue_btn: 'متابعة',
    cta_eyebrow: 'أقرب قليلاً',
    cta_title: 'أفضل ما في دبي، في جيبك.',
    cta_btn: 'انضم إلى أعضاء بيازو',
    settings_preferences: 'التفضيلات',
    settings_live: 'مباشر',
    settings_updated: 'مُحدّث',
    settings_fetching: 'جاري جلب الأسعار المباشرة...',
    contact_nav_home: 'الرئيسية',
    contact_nav_details: 'تفاصيل الاتصال',
    contact_nav_enquiry: 'إرسال استفسار',
    contact_nav_back: 'العودة إلى بيازو',
    contact_hero_eyebrow: 'الباب مفتوح',
    contact_hero_title1: 'دعنا نصنع',
    contact_hero_title2: 'مساحة لك.',
    contact_hero_intro: 'سواء كنت تخطط لإقامة مدروسة، أو تعتني بمنزل في دبي، أو ببساطة تريد وجهة نظر محلية، فريقنا قريب منك.',
    contact_details_eyebrow: 'تجدنا هنا',
    contact_details_title1: 'شخص حقيقي،',
    contact_details_title2: 'في صفك.',
    contact_details_sub: 'لا توجد مراكز اتصال. لا يوجد تسليم. فقط فريق محلي يتمتع بإحساس جيد بالمكان والزمان.',
    contact_whatsapp: 'واتساب',
    contact_email: 'البريد الإلكتروني',
    contact_office: 'المكتب',
    contact_dubai_uae: 'دبي، الإمارات العربية المتحدة',
    contact_po_box: 'ص.ب 118-885',
    contact_enquiry_eyebrow: 'بعض السياق يساعد',
    contact_enquiry_title1: 'أخبرنا ماذا',
    contact_enquiry_title2: 'تحتاج.',
    contact_enquiry_sub: 'اترك بعض التفاصيل وسنعود إليك شخصيًا. للحصول على إجابة فورية، استخدم واتساب أعلاه.',
    contact_enquiry_call: 'اتصل بمكتب بيازو',
    contact_sent_title: 'لقد استلمنا رسالتك.',
    contact_sent_sub: 'شكرًا لك. سيتواصل معك أحد متخصصي منازل عطلات بيازو قريبًا.',
    contact_send_another: 'إرسال رسالة أخرى',
    contact_form_name: 'اسمك',
    contact_form_name_ph: 'كيف تحب أن نناديك؟',
    contact_form_email: 'البريد الإلكتروني أو واتساب',
    contact_form_email_ph: 'أفضل طريقة للوصول إليك',
    contact_form_help: 'بماذا يمكننا المساعدة؟',
    contact_form_help_ph: 'مسكن، عقارك، سؤال عن دبي...',
    contact_form_submit: 'إرسال رسالتك',
    contact_footer_desc: 'مساكن خاصة ومنظور محلي، للطريقة التي ترغب في تجربة دبي بها.',
  },
  fr: {
    perk1_title: 'Des maisons triées sur le volet',
    perk1_desc: 'Chaque résidence est personnellement inspectée et aménagée pour le confort, l\'espace et la lumière naturelle.',
    perk2_title: 'Enregistrement sans clé',
    perk2_desc: 'Arrivez selon votre propre horaire avec un code PIN de serrure intelligente privée — pas d\'attente, pas de hall, pas de tracas.',
    perk3_title: 'Concierge sur appel',
    perk3_desc: 'Réservations de restaurants, transferts aéroport, livraison de courses — notre équipe locale gère les détails pour vous.',
    perk4_title: 'Prix transparents',
    perk4_desc: 'Le prix que vous voyez est le prix que vous payez. Pas de frais cachés, pas de surprises au moment du départ.',
    member_eyebrow: 'Accès privé',
    member_title: 'Faites vôtre Dubaï.',
    member_sub: 'Sauvegardez vos résidences, gardez vos préférences à portée de main et soyez les premiers informés des nouvelles maisons de vacances Biazo.',
    member_email: 'Adresse e-mail',
    member_password: 'Mot de passe',
    member_password_hint: 'Au moins 6 caractères',
    member_create_btn: 'CRÉER UN PROFIL MEMBRE',
    member_already: 'Déjà membre ? Connectez-vous avec votre e-mail.',
    member_welcome: 'Bienvenue chez Biazo.',
    member_welcome_sub: 'Votre profil membre est prêt. Nous enverrons les dernières résidences et des notes sur la ville à',
    member_continue_btn: 'CONTINUER',
    cta_eyebrow: 'Un peu plus près',
    cta_title: 'Le meilleur de Dubaï, dans votre poche.',
    cta_btn: 'REJOINDRE LES MEMBRES BIAZO',
    settings_preferences: 'PRÉFÉRENCES',
    settings_live: 'EN DIRECT',
    settings_updated: 'mis à jour',
    settings_fetching: 'Récupération des taux en direct…',
    contact_nav_home: 'Accueil',
    contact_nav_details: 'Coordonnées',
    contact_nav_enquiry: 'Faire une demande',
    contact_nav_back: 'RETOUR À BIAZO',
    contact_hero_eyebrow: 'La porte est ouverte',
    contact_hero_title1: 'Faisons de',
    contact_hero_title2: 'la place pour vous.',
    contact_hero_intro: 'Que vous planifiiez un séjour réfléchi, que vous vous occupiez d\'une maison à Dubaï ou que vous souhaitiez simplement un point de vue local, notre équipe est à proximité.',
    contact_details_eyebrow: 'Trouvez-nous ici',
    contact_details_title1: 'Une vraie personne,',
    contact_details_title2: 'à vos côtés.',
    contact_details_sub: 'Pas de centres d\'appels. Pas de transferts. Juste une équipe locale avec un bon sens de l\'espace et du temps.',
    contact_whatsapp: 'WhatsApp',
    contact_email: 'E-mail',
    contact_office: 'Bureau',
    contact_dubai_uae: 'Dubaï, Émirats Arabes Unis',
    contact_po_box: 'Boîte Postale 118-885',
    contact_enquiry_eyebrow: 'Un peu de contexte aide',
    contact_enquiry_title1: 'Dites-nous ce dont',
    contact_enquiry_title2: 'vous avez besoin.',
    contact_enquiry_sub: 'Laissez quelques détails et nous vous reviendrons personnellement. Pour une réponse immédiate, utilisez WhatsApp ci-dessus.',
    contact_enquiry_call: 'APPELER LE BUREAU BIAZO',
    contact_sent_title: 'Nous avons votre message.',
    contact_sent_sub: 'Merci. Un spécialiste de Biazo Vacation Homes vous contactera sous peu.',
    contact_send_another: 'ENVOYER UN AUTRE MESSAGE',
    contact_form_name: 'Votre nom',
    contact_form_name_ph: 'Comment devons-nous vous appeler ?',
    contact_form_email: 'E-mail ou WhatsApp',
    contact_form_email_ph: 'Le meilleur moyen de vous joindre',
    contact_form_help: 'En quoi pouvons-nous vous aider ?',
    contact_form_help_ph: 'Une résidence, votre propriété, une question sur Dubaï...',
    contact_form_submit: 'ENVOYER VOTRE MESSAGE',
    contact_footer_desc: 'Des résidences privées et une perspective locale, pour la façon dont vous voulez vivre Dubaï.',
  },
  de: {
    perk1_title: 'Handverlesene Häuser',
    perk1_desc: 'Jede Residenz wird persönlich auf Komfort, Platz und natürliches Licht geprüft und eingerichtet.',
    perk2_title: 'Schlüsselloser Check-in',
    perk2_desc: 'Kommen Sie nach Ihrem eigenen Zeitplan mit einem privaten Smart-Lock-PIN an — kein Warten, keine Lobby, kein Ärger.',
    perk3_title: 'Concierge auf Abruf',
    perk3_desc: 'Restaurantreservierungen, Flughafentransfers, Lebensmittellieferungen — unser lokales Team kümmert sich um die Details.',
    perk4_title: 'Transparente Preise',
    perk4_desc: 'Der Preis, den Sie sehen, ist der Preis, den Sie zahlen. Keine versteckten Gebühren, keine Überraschungen beim Check-out.',
    member_eyebrow: 'Privater Zugang',
    member_title: 'Machen Sie Dubai zu Ihrem.',
    member_sub: 'Speichern Sie Residenzen, behalten Sie Ihre Präferenzen in der Nähe und erfahren Sie als Erster von neuen Biazo-Ferienhäusern.',
    member_email: 'E-Mail-Adresse',
    member_password: 'Passwort',
    member_password_hint: 'Mindestens 6 Zeichen',
    member_create_btn: 'MITGLIEDSPROFIL ERSTELLEN',
    member_already: 'Bereits Mitglied? Melden Sie sich mit Ihrer E-Mail an.',
    member_welcome: 'Willkommen bei Biazo.',
    member_welcome_sub: 'Ihr Mitgliedsprofil ist fertig. Wir senden die neuesten Residenzen und Stadtnotizen an',
    member_continue_btn: 'WEITER',
    cta_eyebrow: 'Ein bisschen näher',
    cta_title: 'Das Beste von Dubai, in Ihrer Tasche.',
    cta_btn: 'BIAZO-MITGLIEDER WERDEN',
    settings_preferences: 'EINSTELLUNGEN',
    settings_live: 'LIVE',
    settings_updated: 'aktualisiert',
    settings_fetching: 'Live-Kurse werden abgerufen…',
    contact_nav_home: 'Startseite',
    contact_nav_details: 'Kontaktdaten',
    contact_nav_enquiry: 'Anfrage stellen',
    contact_nav_back: 'ZURÜCK ZU BIAZO',
    contact_hero_eyebrow: 'Die Tür ist offen',
    contact_hero_title1: 'Lassen Sie uns',
    contact_hero_title2: 'Platz für Sie schaffen.',
    contact_hero_intro: 'Egal, ob Sie einen durchdachten Aufenthalt planen, ein Haus in Dubai betreuen oder einfach nur eine lokale Perspektive wünschen, unser Team ist in der Nähe.',
    contact_details_eyebrow: 'Finden Sie uns hier',
    contact_details_title1: 'Eine echte Person,',
    contact_details_title2: 'in Ihrer Ecke.',
    contact_details_sub: 'Keine Callcenter. Keine Übergaben. Nur ein lokales Team mit einem guten Gespür für Ort und Zeit.',
    contact_whatsapp: 'WhatsApp',
    contact_email: 'E-mail',
    contact_office: 'Büro',
    contact_dubai_uae: 'Dubai, VAE',
    contact_po_box: 'Postfach 118-885',
    contact_enquiry_eyebrow: 'Ein wenig Kontext hilft',
    contact_enquiry_title1: 'Sagen Sie uns, was',
    contact_enquiry_title2: 'Sie brauchen.',
    contact_enquiry_sub: 'Hinterlassen Sie ein paar Details und wir werden uns persönlich bei Ihnen melden. Für eine sofortige Antwort nutzen Sie WhatsApp oben.',
    contact_enquiry_call: 'BIAZO-DESK ANRUFEN',
    contact_sent_title: 'Wir haben Ihre Nachricht erhalten.',
    contact_sent_sub: 'Danke. Ein Spezialist von Biazo Vacation Homes wird sich in Kürze mit Ihnen in Verbindung setzen.',
    contact_send_another: 'WEITERE NACHRICHT SENDEN',
    contact_form_name: 'Ihr Name',
    contact_form_name_ph: 'Wie dürfen wir Sie ansprechen?',
    contact_form_email: 'E-Mail oder WhatsApp',
    contact_form_email_ph: 'Der beste Weg, Sie zu erreichen',
    contact_form_help: 'Wobei können wir helfen?',
    contact_form_help_ph: 'Eine Residenz, Ihr Eigentum, eine Frage zu Dubai...',
    contact_form_submit: 'NACHRICHT SENDEN',
    contact_footer_desc: 'Private Residenzen und lokale Perspektive, für die Art und Weise, wie Sie Dubai erleben möchten.',
  },
  ru: {
    perk1_title: 'Тщательно отобранные дома',
    perk1_desc: 'Каждая резиденция лично проверяется и оформляется с учетом комфорта, пространства и естественного света.',
    perk2_title: 'Заселение без ключа',
    perk2_desc: 'Приезжайте по своему графику с личным PIN-кодом умного замка — никаких ожиданий, никаких лобби, никаких хлопот.',
    perk3_title: 'Консьерж по вызову',
    perk3_desc: 'Бронирование ресторанов, трансферы из аэропорта, доставка продуктов — наша местная команда берет на себя все детали.',
    perk4_title: 'Прозрачные цены',
    perk4_desc: 'Цена, которую вы видите — это цена, которую вы платите. Никаких скрытых комиссий, никаких сюрпризов при выезде.',
    member_eyebrow: 'Частный доступ',
    member_title: 'Сделайте Дубай своим.',
    member_sub: 'Сохраняйте резиденции, держите свои предпочтения под рукой и первыми узнавайте о новых домах для отпуска Biazo.',
    member_email: 'Адрес электронной почты',
    member_password: 'Пароль',
    member_password_hint: 'Не менее 6 символов',
    member_create_btn: 'СОЗДАТЬ ПРОФИЛЬ УЧАСТНИКА',
    member_already: 'Уже участник? Войдите по электронной почте.',
    member_welcome: 'Добро пожаловать в Biazo.',
    member_welcome_sub: 'Ваш профиль участника готов. Мы будем отправлять последние резиденции и заметки о городе на',
    member_continue_btn: 'ПРОДОЛЖИТЬ',
    cta_eyebrow: 'Немного ближе',
    cta_title: 'Лучшее в Дубае — в вашем кармане.',
    cta_btn: 'СТАТЬ УЧАСТНИКОМ BIAZO',
    settings_preferences: 'НАСТРОЙКИ',
    settings_live: 'В ЭФИРЕ',
    settings_updated: 'обновлено',
    settings_fetching: 'Получение актуальных курсов…',
    contact_nav_home: 'Главная',
    contact_nav_details: 'Контактные данные',
    contact_nav_enquiry: 'Оставить заявку',
    contact_nav_back: 'ВЕРНУТЬСЯ К BIAZO',
    contact_hero_eyebrow: 'Двери открыты',
    contact_hero_title1: 'Давайте освободим',
    contact_hero_title2: 'для вас место.',
    contact_hero_intro: 'Планируете ли вы продуманное пребывание, присматриваете за домом в Дубае или просто хотите узнать мнение местных — наша команда всегда рядом.',
    contact_details_eyebrow: 'Найдите нас здесь',
    contact_details_title1: 'Живой человек,',
    contact_details_title2: 'на вашей стороне.',
    contact_details_sub: 'Никаких колл-центров. Никаких передач. Просто местная команда с хорошим чувством места и времени.',
    contact_whatsapp: 'WhatsApp',
    contact_email: 'Электронная почта',
    contact_office: 'Офис',
    contact_dubai_uae: 'Дубай, ОАЭ',
    contact_po_box: 'Почтовый ящик 118-885',
    contact_enquiry_eyebrow: 'Немного контекста поможет',
    contact_enquiry_title1: 'Скажите нам, что',
    contact_enquiry_title2: 'вам нужно.',
    contact_enquiry_sub: 'Оставьте несколько деталей, и мы свяжемся с вами лично. Для немедленного ответа используйте WhatsApp выше.',
    contact_enquiry_call: 'ПОЗВОНИТЬ В СТОЛ BIAZO',
    contact_sent_title: 'Мы получили ваше сообщение.',
    contact_sent_sub: 'Спасибо. Специалист Biazo Vacation Homes свяжется с вами в ближайшее время.',
    contact_send_another: 'ОТПРАВИТЬ ДРУГОЕ СООБЩЕНИЕ',
    contact_form_name: 'Ваше имя',
    contact_form_name_ph: 'Как к вам обращаться?',
    contact_form_email: 'Электронная почта или WhatsApp',
    contact_form_email_ph: 'Лучший способ связаться с вами',
    contact_form_help: 'Чем мы можем помочь?',
    contact_form_help_ph: 'Резиденция, ваша собственность, вопрос о Дубае...',
    contact_form_submit: 'ОТПРАВИТЬ СООБЩЕНИЕ',
    contact_footer_desc: 'Частные резиденции и местная перспектива — для того, как вы хотите узнать Дубай.',
  },
  zh: {
    perk1_title: '精选住宅',
    perk1_desc: '每处住宅都经过亲自检查，并以舒适、空间和自然采光为设计理念。',
    perk2_title: '无钥匙入住',
    perk2_desc: '按照您的日程安排，使用私人智能锁 PIN 码抵达 — 无需等待、无需大堂、无需麻烦。',
    perk3_title: '随叫随到的礼宾服务',
    perk3_desc: '餐厅预订、机场接送、杂货配送 — 我们的本地团队将为您处理细节，让您无后顾之忧。',
    perk4_title: '透明的定价',
    perk4_desc: '您看到的价格就是您支付的价格。退房时没有隐藏费用，没有惊喜。',
    member_eyebrow: '私人访问',
    member_title: '让迪拜成为您的迪拜。',
    member_sub: '保存住宅，密切关注您的偏好，并第一时间了解新的 Biazo 度假屋。',
    member_email: '电子邮件地址',
    member_password: '密码',
    member_password_hint: '至少 6 个字符',
    member_create_btn: '创建会员资料',
    member_already: '已经是会员？用您的电子邮件登录。',
    member_welcome: '欢迎来到 Biazo。',
    member_welcome_sub: '您的会员资料已准备就绪。我们将把最新的住宅和经过深思熟虑的城市笔记发送到',
    member_continue_btn: '继续',
    cta_eyebrow: '再近一点',
    cta_title: '迪拜的精华，尽在您的口袋里。',
    cta_btn: '加入 BIAZO 会员',
    settings_preferences: '偏好',
    settings_live: '实时',
    settings_updated: '更新于',
    settings_fetching: '正在获取实时汇率…',
    contact_nav_home: '首页',
    contact_nav_details: '联系方式',
    contact_nav_enquiry: '提交咨询',
    contact_nav_back: '返回 BIAZO',
    contact_hero_eyebrow: '门是开着的',
    contact_hero_title1: '让我们',
    contact_hero_title2: '为您腾出空间。',
    contact_hero_intro: '无论您是在计划一次周到的住宿、照看迪拜的房屋，还是仅仅想要当地人的观点，我们的团队都在您身边。',
    contact_details_eyebrow: '在这里找到我们',
    contact_details_title1: '一个真实的人，',
    contact_details_title2: '在您身边。',
    contact_details_sub: '没有呼叫中心。没有转接。只有一个对空间和时间有良好感觉的本地团队。',
    contact_whatsapp: 'WhatsApp',
    contact_email: '电子邮件',
    contact_office: '办公室',
    contact_dubai_uae: '阿联酋，迪拜',
    contact_po_box: '邮政信箱 118-885',
    contact_enquiry_eyebrow: '一点背景信息会有所帮助',
    contact_enquiry_title1: '告诉我们',
    contact_enquiry_title2: '您的需求。',
    contact_enquiry_sub: '留下一些细节，我们将亲自回复您。如需立即回复，请使用上方的 WhatsApp。',
    contact_enquiry_call: '致电 BIAZO 服务台',
    contact_sent_title: '我们收到了您的留言。',
    contact_sent_sub: '谢谢。Biazo Vacation Homes 专家将很快与您联系。',
    contact_send_another: '发送另一条留言',
    contact_form_name: '您的姓名',
    contact_form_name_ph: '我们该如何称呼您？',
    contact_form_email: '电子邮件或 WhatsApp',
    contact_form_email_ph: '联系您的最佳方式',
    contact_form_help: '我们能帮什么忙？',
    contact_form_help_ph: '住宅、您的财产、关于迪拜的问题...',
    contact_form_submit: '发送您的留言',
    contact_footer_desc: '私人住宅和当地视角，为您想要体验迪拜的方式。',
  }
};

const indexPath = 'C:/Users/mikia/Downloads/Biazo-Properties/artifacts/biazo-properties/src/i18n/index.ts';
let code = fs.readFileSync(indexPath, 'utf-8');

for (const lang of Object.keys(missingTranslations)) {
  const keysObj = missingTranslations[lang];
  let injectionStr = '';
  for (const [key, val] of Object.entries(keysObj)) {
    injectionStr += "\n      " + key + ": " + JSON.stringify(val) + ",";
  }
  
  const regex = new RegExp("(" + lang + ":\\s*\\{\\s*translation:\\s*\\{)");
  code = code.replace(regex, "$1" + injectionStr);
}

fs.writeFileSync(indexPath, code);
console.log('Successfully injected missing translations.');
