const fs = require('fs');

const missingTranslations = {
  en: {
    booking_select_dates: 'Select Dates & Guests',
    booking_live_avail: 'Check live availability and calculate your stay.',
    booking_checkin: 'Check-In Date',
    booking_checkout: 'Check-Out Date',
    booking_conflict: 'Selected dates are unavailable',
    booking_conflict_desc: 'This residence has a confirmed reservation on overlapping dates. Please pick alternative dates.',
    booking_available: 'Residence is available for these dates!',
    booking_num_guests: 'Number of Guests',
    booking_guest: 'Guest',
    booking_guests: 'Guests',
    booking_max: 'Max',
    booking_primary: 'Primary Guest Details',
    booking_name: 'Full Name *',
    booking_name_ph: 'e.g. Alexander Wright',
    booking_email: 'Email Address *',
    booking_email_ph: 'name@company.com',
    booking_phone: 'Phone / WhatsApp *',
    booking_phone_ph: '+971 50 123 4567',
    booking_special: 'Special Requests (Optional)',
    booking_special_ph: 'Airport transfer, baby cot, early arrival, etc.',
    booking_proceed: 'PROCEED TO PAYMENT & CONFIRMATION',
    booking_fill_warn: 'Please fill in name, email and phone to proceed.',
    booking_pay_options: 'Payment Options',
    booking_edit_dates: 'Edit Dates',
    booking_pay_online: 'Pay Online',
    booking_pay_later: 'Hold & Pay Later',
    booking_whatsapp: 'WhatsApp Desk',
    booking_encrypted: '256-Bit SSL Encrypted',
    booking_name_card: 'Name on Card *',
    booking_name_card_ph: 'Name as it appears on card',
    booking_card_num: 'Card Number *',
    booking_expires: 'Expires *',
    booking_cvc: 'CVC / CVV *',
    booking_pay_upon: 'Pay Upon Check-in',
    booking_pay_upon_desc: 'Your reservation is instantly confirmed and held under your name. You can pay with Card, Cash, or Bank Wire when you arrive in Dubai. Free cancellation up to 48 hours before check-in.',
    booking_guarantee: 'Credit Card Number for Guarantee *',
    booking_concierge: 'Direct Concierge Assistance',
    booking_concierge_desc: 'Prefer to speak with our reservations desk directly? Click below to send your reservation details to our WhatsApp team for bespoke invoicing or corporate wire transfers.',
    booking_open_wa: 'OPEN CONCIERGE WHATSAPP (+971 54 4937128)',
    booking_submitting: 'SUBMITTING YOUR BOOKING...',
    booking_request: 'REQUEST BOOKING — ',
    booking_confirm: 'GUARANTEE & CONFIRM RESERVATION',
    booking_summary: 'Price Summary',
    booking_nights: 'nights',
    booking_cleaning: 'Departure Housekeeping & Linen Fee',
    booking_tourism: 'Dubai Tourism Dirham Fee',
    booking_vat: 'UAE Value Added Tax (5% VAT)',
    booking_total: 'Total Due',
    booking_incl1: 'Included: High-speed Wi-Fi & Nespresso',
    booking_incl2: '24/7 Local Concierge & Keyless Entry',
    booking_incl3: 'Free cancellation up to 48 hours before stay',
    booking_confirmed: 'Reservation Confirmed',
    booking_welcoming: 'We look forward to welcoming you.',
    booking_voucher: 'A confirmation voucher and receipt have been issued for',
    booking_ref: 'Booking Reference',
    booking_status: 'Payment Status',
    booking_paid: 'PAID IN FULL',
    booking_guaranteed: 'CARD GUARANTEED',
    booking_checkin_time: 'Check-In (from 3:00 PM)',
    booking_checkout_time: 'Check-Out (by 11:00 AM)',
    booking_duration: 'Duration & Guests',
    booking_Nights: 'Nights',
    booking_total_amt: 'Total Amount',
    booking_smart_lock: 'Keyless Smart Lock Access',
    booking_pin: 'PIN:',
    booking_activates: 'Activates on',
    booking_at: 'at 3:00 PM',
    booking_print: 'PRINT / SAVE VOUCHER',
    booking_back: 'BACK TO RESIDENCES'
  },
  ar: {
    booking_select_dates: 'اختر التواريخ والضيوف',
    booking_live_avail: 'تحقق من التوفر المباشر واحسب إقامتك.',
    booking_checkin: 'تاريخ تسجيل الوصول',
    booking_checkout: 'تاريخ تسجيل المغادرة',
    booking_conflict: 'التواريخ المحددة غير متاحة',
    booking_conflict_desc: 'يوجد حجز مؤكد في هذه التواريخ. يرجى اختيار تواريخ بديلة.',
    booking_available: 'المسكن متاح في هذه التواريخ!',
    booking_num_guests: 'عدد الضيوف',
    booking_guest: 'ضيف',
    booking_guests: 'ضيوف',
    booking_max: 'الحد الأقصى',
    booking_primary: 'تفاصيل الضيف الرئيسي',
    booking_name: 'الاسم الكامل *',
    booking_name_ph: 'مثال: ألكسندر رايت',
    booking_email: 'عنوان البريد الإلكتروني *',
    booking_email_ph: 'name@company.com',
    booking_phone: 'الهاتف / واتساب *',
    booking_phone_ph: '+971 50 123 4567',
    booking_special: 'طلبات خاصة (اختياري)',
    booking_special_ph: 'نقل من المطار، سرير أطفال، وصول مبكر، إلخ.',
    booking_proceed: 'المتابعة إلى الدفع والتأكيد',
    booking_fill_warn: 'يرجى ملء الاسم والبريد الإلكتروني والهاتف للمتابعة.',
    booking_pay_options: 'خيارات الدفع',
    booking_edit_dates: 'تعديل التواريخ',
    booking_pay_online: 'الدفع عبر الإنترنت',
    booking_pay_later: 'حجز والدفع لاحقًا',
    booking_whatsapp: 'مكتب واتساب',
    booking_encrypted: 'مشفر 256-Bit SSL',
    booking_name_card: 'الاسم على البطاقة *',
    booking_name_card_ph: 'الاسم كما يظهر على البطاقة',
    booking_card_num: 'رقم البطاقة *',
    booking_expires: 'تاريخ الانتهاء *',
    booking_cvc: 'CVC / CVV *',
    booking_pay_upon: 'الدفع عند تسجيل الوصول',
    booking_pay_upon_desc: 'تم تأكيد حجزك فورًا وهو محفوظ باسمك. يمكنك الدفع بالبطاقة أو نقدًا أو بالتحويل البنكي عند وصولك إلى دبي. إلغاء مجاني حتى 48 ساعة قبل تسجيل الوصول.',
    booking_guarantee: 'رقم بطاقة الائتمان للضمان *',
    booking_concierge: 'مساعدة الكونسيرج المباشرة',
    booking_concierge_desc: 'هل تفضل التحدث مع مكتب الحجوزات لدينا مباشرة؟ انقر أدناه لإرسال تفاصيل حجزك إلى فريق واتساب الخاص بنا.',
    booking_open_wa: 'افتح واتساب الكونسيرج (+971 54 4937128)',
    booking_submitting: 'جاري إرسال حجزك...',
    booking_request: 'طلب حجز — ',
    booking_confirm: 'ضمان وتأكيد الحجز',
    booking_summary: 'ملخص السعر',
    booking_nights: 'ليالي',
    booking_cleaning: 'رسوم التنظيف والمغادرة',
    booking_tourism: 'رسوم درهم دبي السياحي',
    booking_vat: 'ضريبة القيمة المضافة (5%)',
    booking_total: 'الإجمالي المستحق',
    booking_incl1: 'مشمول: واي فاي عالي السرعة ونيسبريسو',
    booking_incl2: 'كونسيرج محلي 24/7 ودخول بدون مفتاح',
    booking_incl3: 'إلغاء مجاني حتى 48 ساعة قبل الإقامة',
    booking_confirmed: 'تم تأكيد الحجز',
    booking_welcoming: 'نحن نتطلع للترحيب بك.',
    booking_voucher: 'تم إصدار قسيمة تأكيد وإيصال لـ',
    booking_ref: 'مرجع الحجز',
    booking_status: 'حالة الدفع',
    booking_paid: 'مدفوع بالكامل',
    booking_guaranteed: 'بطاقة مضمونة',
    booking_checkin_time: 'تسجيل الوصول (من 3:00 مساءً)',
    booking_checkout_time: 'تسجيل المغادرة (قبل 11:00 صباحًا)',
    booking_duration: 'المدة والضيوف',
    booking_Nights: 'ليالي',
    booking_total_amt: 'المبلغ الإجمالي',
    booking_smart_lock: 'وصول بدون مفتاح',
    booking_pin: 'الرقم السري:',
    booking_activates: 'يتم تفعيله في',
    booking_at: 'الساعة 3:00 مساءً',
    booking_print: 'طباعة / حفظ القسيمة',
    booking_back: 'العودة إلى المساكن'
  },
  fr: {
    booking_select_dates: 'Sélectionnez les dates et les invités',
    booking_live_avail: 'Vérifiez la disponibilité en direct et calculez votre séjour.',
    booking_checkin: 'Date d\'arrivée',
    booking_checkout: 'Date de départ',
    booking_conflict: 'Les dates sélectionnées sont indisponibles',
    booking_conflict_desc: 'Cette résidence a une réservation confirmée sur des dates chevauchantes. Veuillez choisir d\'autres dates.',
    booking_available: 'La résidence est disponible pour ces dates !',
    booking_num_guests: 'Nombre d\'invités',
    booking_guest: 'Invité',
    booking_guests: 'Invités',
    booking_max: 'Max',
    booking_primary: 'Détails de l\'invité principal',
    booking_name: 'Nom complet *',
    booking_name_ph: 'ex. Alexander Wright',
    booking_email: 'Adresse e-mail *',
    booking_email_ph: 'name@company.com',
    booking_phone: 'Téléphone / WhatsApp *',
    booking_phone_ph: '+971 50 123 4567',
    booking_special: 'Demandes spéciales (Optionnel)',
    booking_special_ph: 'Transfert aéroport, lit bébé, arrivée anticipée, etc.',
    booking_proceed: 'PASSER AU PAIEMENT ET À LA CONFIRMATION',
    booking_fill_warn: 'Veuillez remplir le nom, l\'e-mail et le téléphone pour continuer.',
    booking_pay_options: 'Options de paiement',
    booking_edit_dates: 'Modifier les dates',
    booking_pay_online: 'Payer en ligne',
    booking_pay_later: 'Réserver et payer plus tard',
    booking_whatsapp: 'Bureau WhatsApp',
    booking_encrypted: 'Crypté 256-Bit SSL',
    booking_name_card: 'Nom sur la carte *',
    booking_name_card_ph: 'Nom tel qu\'il apparaît sur la carte',
    booking_card_num: 'Numéro de carte *',
    booking_expires: 'Expire le *',
    booking_cvc: 'CVC / CVV *',
    booking_pay_upon: 'Payer à l\'arrivée',
    booking_pay_upon_desc: 'Votre réservation est instantanément confirmée et conservée à votre nom. Vous pouvez payer par carte, espèces ou virement bancaire lors de votre arrivée à Dubaï. Annulation gratuite jusqu\'à 48 heures avant l\'arrivée.',
    booking_guarantee: 'Numéro de carte de crédit pour garantie *',
    booking_concierge: 'Assistance Concierge Directe',
    booking_concierge_desc: 'Vous préférez parler directement à notre bureau des réservations ? Cliquez ci-dessous pour envoyer les détails de votre réservation à notre équipe WhatsApp.',
    booking_open_wa: 'OUVRIR WHATSAPP CONCIERGE (+971 54 4937128)',
    booking_submitting: 'SOUMISSION DE VOTRE RÉSERVATION...',
    booking_request: 'DEMANDER LA RÉSERVATION — ',
    booking_confirm: 'GARANTIR & CONFIRMER LA RÉSERVATION',
    booking_summary: 'Résumé des prix',
    booking_nights: 'nuits',
    booking_cleaning: 'Frais de ménage de départ',
    booking_tourism: 'Frais de tourisme Dirham de Dubaï',
    booking_vat: 'Taxe sur la valeur ajoutée (5% TVA)',
    booking_total: 'Total à payer',
    booking_incl1: 'Inclus : Wi-Fi haut débit et Nespresso',
    booking_incl2: 'Concierge local 24/7 et entrée sans clé',
    booking_incl3: 'Annulation gratuite jusqu\'à 48 heures avant le séjour',
    booking_confirmed: 'Réservation Confirmée',
    booking_welcoming: 'Nous sommes impatients de vous accueillir.',
    booking_voucher: 'Un bon de confirmation et un reçu ont été émis pour',
    booking_ref: 'Référence de réservation',
    booking_status: 'Statut du paiement',
    booking_paid: 'PAYÉ EN TOTALITÉ',
    booking_guaranteed: 'CARTE GARANTIE',
    booking_checkin_time: 'Arrivée (à partir de 15h00)',
    booking_checkout_time: 'Départ (avant 11h00)',
    booking_duration: 'Durée et invités',
    booking_Nights: 'Nuits',
    booking_total_amt: 'Montant Total',
    booking_smart_lock: 'Accès sans clé (Serrure Intelligente)',
    booking_pin: 'Code PIN :',
    booking_activates: 'S\'active le',
    booking_at: 'à 15h00',
    booking_print: 'IMPRIMER / SAUVEGARDER LE BON',
    booking_back: 'RETOUR AUX RÉSIDENCES'
  },
  de: {
    booking_select_dates: 'Daten & Gäste auswählen',
    booking_live_avail: 'Prüfen Sie die Live-Verfügbarkeit und berechnen Sie Ihren Aufenthalt.',
    booking_checkin: 'Check-in-Datum',
    booking_checkout: 'Check-out-Datum',
    booking_conflict: 'Ausgewählte Daten sind nicht verfügbar',
    booking_conflict_desc: 'Für diese Residenz liegt an überschneidenden Daten eine bestätigte Reservierung vor. Bitte wählen Sie alternative Daten.',
    booking_available: 'Die Residenz ist für diese Daten verfügbar!',
    booking_num_guests: 'Anzahl der Gäste',
    booking_guest: 'Gast',
    booking_guests: 'Gäste',
    booking_max: 'Max',
    booking_primary: 'Angaben zum Hauptgast',
    booking_name: 'Vollständiger Name *',
    booking_name_ph: 'z.B. Alexander Wright',
    booking_email: 'E-Mail-Adresse *',
    booking_email_ph: 'name@company.com',
    booking_phone: 'Telefon / WhatsApp *',
    booking_phone_ph: '+971 50 123 4567',
    booking_special: 'Besondere Wünsche (Optional)',
    booking_special_ph: 'Flughafentransfer, Babybett, frühe Anreise usw.',
    booking_proceed: 'WEITER ZUR ZAHLUNG & BESTÄTIGUNG',
    booking_fill_warn: 'Bitte füllen Sie Name, E-Mail und Telefon aus, um fortzufahren.',
    booking_pay_options: 'Zahlungsoptionen',
    booking_edit_dates: 'Daten bearbeiten',
    booking_pay_online: 'Online zahlen',
    booking_pay_later: 'Reservieren & Später Zahlen',
    booking_whatsapp: 'WhatsApp Schreibtisch',
    booking_encrypted: '256-Bit SSL verschlüsselt',
    booking_name_card: 'Name auf der Karte *',
    booking_name_card_ph: 'Name wie auf der Karte angegeben',
    booking_card_num: 'Kartennummer *',
    booking_expires: 'Läuft ab *',
    booking_cvc: 'CVC / CVV *',
    booking_pay_upon: 'Zahlung beim Check-in',
    booking_pay_upon_desc: 'Ihre Reservierung wird sofort bestätigt und unter Ihrem Namen gehalten. Sie können bei Ihrer Ankunft in Dubai mit Karte, Bargeld oder Banküberweisung bezahlen. Kostenlose Stornierung bis 48 Stunden vor Check-in.',
    booking_guarantee: 'Kreditkartennummer als Garantie *',
    booking_concierge: 'Direkte Concierge-Unterstützung',
    booking_concierge_desc: 'Möchten Sie lieber direkt mit unserer Reservierungsabteilung sprechen? Klicken Sie unten, um Ihre Reservierungsdetails an unser WhatsApp-Team zu senden.',
    booking_open_wa: 'CONCIERGE WHATSAPP ÖFFNEN (+971 54 4937128)',
    booking_submitting: 'IHRE BUCHUNG WIRD ÜBERMITTELT...',
    booking_request: 'BUCHUNG ANFRAGEN — ',
    booking_confirm: 'GARANTIEREN & RESERVIERUNG BESTÄTIGEN',
    booking_summary: 'Preiszusammenfassung',
    booking_nights: 'Nächte',
    booking_cleaning: 'Abreinigung & Bettwäsche Gebühr',
    booking_tourism: 'Dubai Tourismus Dirham Gebühr',
    booking_vat: 'VAE Mehrwertsteuer (5% MwSt)',
    booking_total: 'Gesamtsumme',
    booking_incl1: 'Inklusive: High-Speed-WLAN & Nespresso',
    booking_incl2: '24/7 lokaler Concierge & schlüsselloser Zugang',
    booking_incl3: 'Kostenlose Stornierung bis 48 Stunden vor Aufenthalt',
    booking_confirmed: 'Reservierung Bestätigt',
    booking_welcoming: 'Wir freuen uns darauf, Sie begrüßen zu dürfen.',
    booking_voucher: 'Ein Bestätigungsgutschein und eine Quittung wurden ausgestellt für',
    booking_ref: 'Buchungsreferenz',
    booking_status: 'Zahlungsstatus',
    booking_paid: 'VOLLSTÄNDIG BEZAHLT',
    booking_guaranteed: 'KARTE GARANTIERT',
    booking_checkin_time: 'Check-In (ab 15:00 Uhr)',
    booking_checkout_time: 'Check-Out (bis 11:00 Uhr)',
    booking_duration: 'Dauer & Gäste',
    booking_Nights: 'Nächte',
    booking_total_amt: 'Gesamtbetrag',
    booking_smart_lock: 'Schlüsselloser Smart-Lock-Zugang',
    booking_pin: 'PIN:',
    booking_activates: 'Wird aktiviert am',
    booking_at: 'um 15:00 Uhr',
    booking_print: 'GUTSCHEIN DRUCKEN / SPEICHERN',
    booking_back: 'ZURÜCK ZU DEN RESIDENZEN'
  },
  ru: {
    booking_select_dates: 'Выберите даты и гостей',
    booking_live_avail: 'Проверьте доступность и рассчитайте свое пребывание.',
    booking_checkin: 'Дата заезда',
    booking_checkout: 'Дата выезда',
    booking_conflict: 'Выбранные даты недоступны',
    booking_conflict_desc: 'На эти даты уже есть подтвержденное бронирование. Пожалуйста, выберите другие даты.',
    booking_available: 'Резиденция доступна на эти даты!',
    booking_num_guests: 'Количество гостей',
    booking_guest: 'Гость',
    booking_guests: 'Гостей',
    booking_max: 'Макс',
    booking_primary: 'Данные основного гостя',
    booking_name: 'Полное имя *',
    booking_name_ph: 'например, Александр Райт',
    booking_email: 'Адрес электронной почты *',
    booking_email_ph: 'name@company.com',
    booking_phone: 'Телефон / WhatsApp *',
    booking_phone_ph: '+971 50 123 4567',
    booking_special: 'Особые пожелания (необязательно)',
    booking_special_ph: 'Трансфер из аэропорта, детская кроватка и т. д.',
    booking_proceed: 'ПЕРЕЙТИ К ОПЛАТЕ И ПОДТВЕРЖДЕНИЮ',
    booking_fill_warn: 'Пожалуйста, заполните имя, email и телефон.',
    booking_pay_options: 'Варианты оплаты',
    booking_edit_dates: 'Изменить даты',
    booking_pay_online: 'Оплатить онлайн',
    booking_pay_later: 'Бронь и оплата на месте',
    booking_whatsapp: 'Чат WhatsApp',
    booking_encrypted: '256-Bit SSL Зашифровано',
    booking_name_card: 'Имя на карте *',
    booking_name_card_ph: 'Как указано на карте',
    booking_card_num: 'Номер карты *',
    booking_expires: 'Действует до *',
    booking_cvc: 'CVC / CVV *',
    booking_pay_upon: 'Оплата при заезде',
    booking_pay_upon_desc: 'Бронирование моментально подтверждается на ваше имя. Вы можете оплатить картой, наличными или переводом по прибытии в Дубай. Бесплатная отмена за 48 часов до заезда.',
    booking_guarantee: 'Номер кредитной карты для гарантии *',
    booking_concierge: 'Прямая связь с консьержем',
    booking_concierge_desc: 'Предпочитаете общаться напрямую с отделом бронирования? Нажмите ниже, чтобы отправить детали в нашу команду WhatsApp.',
    booking_open_wa: 'ОТКРЫТЬ WHATSAPP КОНСЬЕРЖА (+971 54 4937128)',
    booking_submitting: 'ОТПРАВКА БРОНИРОВАНИЯ...',
    booking_request: 'ЗАПРОСИТЬ БРОНИРОВАНИЕ — ',
    booking_confirm: 'ГАРАНТИРОВАТЬ И ПОДТВЕРДИТЬ БРОНЬ',
    booking_summary: 'Сводка цен',
    booking_nights: 'ночей',
    booking_cleaning: 'Сбор за уборку и белье',
    booking_tourism: 'Туристический сбор Дубая',
    booking_vat: 'НДС ОАЭ (5%)',
    booking_total: 'К оплате',
    booking_incl1: 'Включено: Высокоскоростной Wi-Fi и Nespresso',
    booking_incl2: 'Круглосуточный консьерж и доступ без ключа',
    booking_incl3: 'Бесплатная отмена за 48 часов',
    booking_confirmed: 'Бронирование подтверждено',
    booking_welcoming: 'Мы с нетерпением ждем вас.',
    booking_voucher: 'Ваучер подтверждения и квитанция выданы для',
    booking_ref: 'Номер бронирования',
    booking_status: 'Статус оплаты',
    booking_paid: 'ПОЛНОСТЬЮ ОПЛАЧЕНО',
    booking_guaranteed: 'КАРТА ГАРАНТИРОВАНА',
    booking_checkin_time: 'Заезд (с 15:00)',
    booking_checkout_time: 'Выезд (до 11:00)',
    booking_duration: 'Продолжительность и гости',
    booking_Nights: 'Ночей',
    booking_total_amt: 'Общая сумма',
    booking_smart_lock: 'Доступ без ключа',
    booking_pin: 'PIN-код:',
    booking_activates: 'Активируется',
    booking_at: 'в 15:00',
    booking_print: 'ПЕЧАТЬ / СОХРАНИТЬ ВАУЧЕР',
    booking_back: 'ВЕРНУТЬСЯ К РЕЗИДЕНЦИЯМ'
  },
  zh: {
    booking_select_dates: '选择日期和人数',
    booking_live_avail: '查看实时空房情况并计算您的住宿。',
    booking_checkin: '入住日期',
    booking_checkout: '退房日期',
    booking_conflict: '所选日期不可用',
    booking_conflict_desc: '该住宅在重叠日期已有已确认的预订。请选择其他日期。',
    booking_available: '住宅在这些日期可用！',
    booking_num_guests: '客人数量',
    booking_guest: '客人',
    booking_guests: '客人',
    booking_max: '最多',
    booking_primary: '主要客人详情',
    booking_name: '全名 *',
    booking_name_ph: '例如：Alexander Wright',
    booking_email: '电子邮件地址 *',
    booking_email_ph: 'name@company.com',
    booking_phone: '电话 / WhatsApp *',
    booking_phone_ph: '+971 50 123 4567',
    booking_special: '特别要求 (可选)',
    booking_special_ph: '机场接送，婴儿床，提前入住等。',
    booking_proceed: '继续付款和确认',
    booking_fill_warn: '请填写姓名，电子邮件和电话以继续。',
    booking_pay_options: '付款选项',
    booking_edit_dates: '编辑日期',
    booking_pay_online: '在线支付',
    booking_pay_later: '预订并在之后付款',
    booking_whatsapp: 'WhatsApp 服务台',
    booking_encrypted: '256-Bit SSL 加密',
    booking_name_card: '持卡人姓名 *',
    booking_name_card_ph: '与卡上显示的姓名相同',
    booking_card_num: '卡号 *',
    booking_expires: '到期日 *',
    booking_cvc: 'CVC / CVV *',
    booking_pay_upon: '入住时付款',
    booking_pay_upon_desc: '您的预订会立即确认并保留在您的名下。您在抵达迪拜时可以使用信用卡，现金或银行电汇付款。入住前 48 小时免费取消。',
    booking_guarantee: '用于担保的信用卡号 *',
    booking_concierge: '直接礼宾协助',
    booking_concierge_desc: '喜欢直接与我们的预订部交谈吗？点击下方将您的预订详情发送给我们的 WhatsApp 团队。',
    booking_open_wa: '打开礼宾 WhatsApp (+971 54 4937128)',
    booking_submitting: '正在提交您的预订...',
    booking_request: '请求预订 — ',
    booking_confirm: '担保并确认预订',
    booking_summary: '价格明细',
    booking_nights: '晚',
    booking_cleaning: '退房清洁和布草费',
    booking_tourism: '迪拜旅游迪拉姆费',
    booking_vat: '阿联酋增值税 (5% VAT)',
    booking_total: '应付总额',
    booking_incl1: '包含：高速 Wi-Fi 和 Nespresso',
    booking_incl2: '24/7 当地礼宾和无钥匙进入',
    booking_incl3: '入住前 48 小时免费取消',
    booking_confirmed: '预订已确认',
    booking_welcoming: '我们期待着您的光临。',
    booking_voucher: '确认凭证和收据已签发给',
    booking_ref: '预订参考',
    booking_status: '付款状态',
    booking_paid: '已全额付款',
    booking_guaranteed: '信用卡已担保',
    booking_checkin_time: '入住 (下午 3:00 起)',
    booking_checkout_time: '退房 (上午 11:00 前)',
    booking_duration: '住宿时长和人数',
    booking_Nights: '晚',
    booking_total_amt: '总金额',
    booking_smart_lock: '无钥匙智能锁访问',
    booking_pin: 'PIN码：',
    booking_activates: '激活时间',
    booking_at: '下午 3:00',
    booking_print: '打印 / 保存凭证',
    booking_back: '返回住宅列表'
  }
};

const indexPath = 'C:/Users/mikia/Downloads/Biazo-Properties/artifacts/biazo-properties/src/i18n/index.ts';
let code = fs.readFileSync(indexPath, 'utf-8');

for (const lang of Object.keys(missingTranslations)) {
  const keysObj = missingTranslations[lang];
  let injectionStr = '';
  for (const [key, val] of Object.entries(keysObj)) {
    injectionStr += "\n      " + key + ": " + JSON.stringify(val) + ",";
  }
  
  const regex = new RegExp("(" + lang + ":\\s*\\{\\s*translation:\\s*\\{)");
  code = code.replace(regex, "$1" + injectionStr);
}

fs.writeFileSync(indexPath, code);
console.log('Successfully injected missing translations for BookingModal.');
